### ISSUE TITLE
client.py does not get response

### ISSUE THREAD

**Issue by Haxxeris** [aaroncdc/etherbot#1]
When giving input in the client.py, the server will not respond with an answer, but recognizes the connection.

**Comment by aaroncdc** [comment]
It should be fixed now.
The TCP server was a feature I used for testing purposes only and didn't work correctly. Thus why I commented it, since the main purpose of the bot was to use it with a web browser anyway. The problem was that the TCP server was not loading, and you were connecting to the HTTP server instead (Or rather the HTTP server was blocking it).

Now, if you uncomment the lines in the code to enable the TCP server, you should be able to connect through TCP. However, connecting to both is not possible (Because both are in blocking mode and only one will work at a time). So you must either use TCP, or HTTP.

**Comment by Haxxeris** [comment]
Thank you very much for fixing it.
